### ISSUE TITLE
AttributeError: 'module' object has no attribute 'flow_direction_d_inf'

### ISSUE THREAD

**Issue by bowenbelongstonature** [natcap/pygeoprocessing#242]
Hi guys.
I'm using pygeoprocessing2.0.0 and I got this error.
Did some changes make for this atrribute?

**Comment by dcdenu4** [comment]
Hi @bowenbelongstonature,

Could you give us a little more information on how you're using `pygeoprocessing`?

- Are you running from the command line? A script? (feel free to share snippets of code)
- What is the signature of the pygeoprocessing call you are making?
- Did you install pygeoprocessing through `pip` or `conda`?
- Could you try the latest pygeoprocessing release, `2.3.3post0` and see if you experience this issue?

Thanks

**Comment by phargogh** [comment]
@bowenbelongstonature It also looks like you might be trying to use pygeoprocessing's D-Infinity routing algorithm, which was removed in pygeoprocessing 1.0.  This has been replaced with a new multiple flow direction routing function that provides a similar weighted flow into multiple pixels, but doesn't have some of the same undefined edge cases that d-infinity had.

In case this is what you're looking for, the MFD routing functions can be found at:
* `pygeoprocessing.routing.flow_dir_mfd`
* `pygeoprocessing.routing.flow_accumulation_mfd`
* `pygeoprocessing.routing.distance_to_channel_mfd`

But in case this isn't what you're looking for, the information @dcdenu4 mentioned would help us get to the bottom of this.  Thanks!

**Comment by bowenbelongstonature** [comment]
@dcdenu4 @phargogh  
I'm doing this as a script (original script is [https://github.com/OGGM/partitioning](url) )
My pygeoprocessing was installed by pip. 

Actually I have question on the version of pygeoprocessing since my python version is 2.7 and maybe the pygeoprocessing2.0.0 is not supported on python2.7? (But...anyway, I installed it through `pip install pygeoprocessing==2.0.0`)

2.3.3post0 cannot be installed under my environment.

I tried to install `pygeoprocessing0.6.0` since it has the `flow_direction_d_inf`. I run the script and get:
 `File "*/pygeoprocessing/routing/routing.py", line113, in flow_accumulation
      constant_flux_source_uri=geoprocessing.temporary_filename(

AttributeError: 'module' object has no attribute 'temporary_filename`

**Comment by phargogh** [comment]
Hi @bowenbelongstonature , in order to address that `AttributeError` about `temporary_filename`, you'll need to `pip install pygeoprocessing==0.3.3`.

As for python 2.7 support, the latest version of pygeoprocessing that supports python 2.7 is `pygeoprocessing==1.6.1`, but just to reiterate what I mentioned before, 1.6.1 does not include the d-infinity routing algorithm.  So your best bet will be to install 0.3.3 and to go from there.

**Comment by bowenbelongstonature** [comment]
@phargogh yes, I'm working with pygeoprocessing==0.3.3. And I have another question: what's the meaning of `snap_distance` and `flow_threshold` in `delineate_watershed` of 0.3.3. Plus, I notice there are no these two params in `pygeoprocessing.routing.delineate_watersheds_d8()` of latest version.

**Comment by phargogh** [comment]
In `pygeoprocessing==0.3.3`, the `flow_threshold` parameter would be applied to a flow accumulation layer in order to identify stream pixels.  A stream pixel is a pixel where the number of pixels flowing into that pixel is greater than or equal to `flow_threshold`.  Then, for each point in the vector layer, the watershed delineation function would search within `snap_distance` pixels to find the closest stream pixel and then update the point's geometry to be directly on top of the stream pixel.

In `pygeoprocessing==2.3.3`, watershed delineation is more orthogonal, so it will simply delineate watersheds from whatever geometries you give it.  The lack of a snap distance feature is somewhat made up for by the fact that this version of watershed delineation allows you to provide geometries of any type.

If you're looking for the snapping functionality, we moved it to [`natcap.invest.delineateit`](https://github.com/natcap/invest/blob/main/src/natcap/invest/delineateit/delineateit.py#L455), as part of the InVEST suite.

**Comment by bowenbelongstonature** [comment]
OK. And do you have any advice about `routing.delineate_watershed` in current version? I just find `pygeoprocessing.routing.watershed.delineate_watersheds_d8()`. Will this work if my inputs come from the MFD routing functions? 

Besides, there is only one way, the `flow_direction_d_inf`, in 0.3.3 to calculate flow direction but two, `d8 and mfd`, in current version, right?

And, do you know how to calculate `stream raster` now?

**Comment by phargogh** [comment]
> Will this work if my inputs come from the MFD routing functions?

No, `pygeoprocessing.routing.watershed.delineate_watersheds_d8()` is specifically for the D8 routing algorithm.  Pygeoprocessing does not currently offer MFD watershed delineation.

> And do you have any advice about `routing.delineate_watershed` in current version?

The only watershed delineation that pygeoprocessing currently offers is D8 watershed delineation.  This should be fine for most use cases.  If you need the old version of watershed delineation, the most direct solution will be to specifically install `pygeoprocessing==0.3.3`.


> Besides, there is only one way, the flow_direction_d_inf, in 0.3.3 to calculate flow direction but two, d8 and mfd, in current version, right?

Yes, `Pygeoprocessing==2.3.3` offers both D8 and MFD flow direction.  `Pygeoprocessing==0.3.3` appears to only offer standalone D-Infinity flow direction

> And, do you know how to calculate stream raster now?

Using D8 routing in `pygeoprocessing==2.3.3`, a stream raster can be calculated by:

1. Calculating flow accumulation with `pygeoprocessing.routing.flow_accumulation_d8`
2. Calling `pygeoprocessing.raster_calculator` on the flow accumulation raster and setting a threshold flow accumulation value, anything overwhich is a stream.  InVEST has an example of such a thresholding function here: https://github.com/natcap/invest/blob/main/src/natcap/invest/delineateit/delineateit.py#L299

Using MFD routing, determining which pixels are streams is much more complicated, so this can be done with https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/routing/routing.pyx#L2932.

**Comment by emlys** [comment]
Closing because it sounds like the question was answered
