### ISSUE TITLE
Release for GDAL 3

### ISSUE THREAD

**Issue by mwalvarenga** [natcap/pygeoprocessing#58]
I see you're working on a new release (2.0) with support for GDAL 3 which is great :) What's the plan for this release? Is there more work to be done or will it be available soon?

Thanks in advance!

**Comment by phargogh** [comment]
Hey @mwalvarenga , the full release plan is over at the 2.0 milestone in the issue tracker: https://github.com/natcap/pygeoprocessing/milestone/1  so that's what we're still planning on doing before the release.  Hard to say when the release will be other than "when it's ready" :) 

In the meantime, if you'd like a development preview of the 2.0 release (which already uses GDAL 3.x), you can always `pip install git+https://github.com/natcap/pygeoprocessing.git@release/2.0#egg=pygeoprocessing`.

Hope this helps!

**Comment by mwalvarenga** [comment]
Nice, I will have a look! Thanks.
I actually managed to install GDAL 2.4.2 and installed pygeoprocessing 1.9.2. 
I am trying to use 'delineate_watershed' which was working fine when I had pygeoprocessing 0.3.0 with GDAL 2.2.4 in python 2.7. But with pygeoprocessing 1.9.2 I get the error: AttributeError("module 'pygeoprocessing.routing' has no attribute 'delineate_watershed'"
Can I still have the functionality of 'delineate_watershed' with the version 1.9.2?

**Comment by phargogh** [comment]
`pygeoprocessing.routing.delineate_watershed` has been replaced with `pygeoprocessing.routing.delineate_watersheds_d8` as of pygeoprocessing 1.7.0.  The usage has changed a fair bit as well: pygeoprocessing's API changed dramatically with version 1.0, and you'll need to determine flow direction before delineating watersheds, and fill pits if you don't already have a ptfilled DEM.  Here's an example of how to delineate watersheds with pygeoprocessing 1.9.2:

```python
import pygeoprocessing.routing

source_dem_path = 'source.tif'
filled_dem_path = 'filled.tif'
flow_dir_path = 'flow_dir_d8.tif'
outflow_vector = 'outflow_features.shp'
watersheds_vector = 'watersheds.gpkg'

pygeoprocessing.routing.fill_pits((source_dem_path, 1), filled_dem_path)
pygeoprocessing.routing.flow_dir_d8((filled_dem_path, 1), flow_dir_path)
pygeoprocessing.routing.delineate_watersheds_d8((flow_dir_path, 1), outflow_vector, watersheds_vector)
```

FYI, watershed delineation has changed a bit.  D8 is used instead of D-infinity, and outflow features can be of any type, not just points.

**Comment by richpsharp** [comment]
Seems like this question was answered, so I'm closing it. Feel free to re-open if there's a follow up.
